ARG MONGO_VERSION

FROM mongo:${MONGO_VERSION}

# Start MongoDB in replica set mode in the background
ENTRYPOINT mongod --port $MONGO_REPLICA_PORT --replSet rs0 --bind_ip 0.0.0.0 & MONGOD_PID=$!; \
# Initialize the replica set
INIT_REPL_CMD="rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: '$MONGO_REPLICA_HOST:$MONGO_REPLICA_PORT' }] })"; \
until ($MONGO_COMMAND admin --port $MONGO_REPLICA_PORT --eval "$INIT_REPL_CMD"); do sleep 1; done; \
# Create the root user
INIT_USER_CMD="db.getSiblingDB('admin').createUser({ user: '$MONGO_INITDB_ROOT_USERNAME', pwd: '$MONGO_INITDB_ROOT_PASSWORD', roles: [ { role: 'root', db: 'admin' } ] })"; \
$MONGO_COMMAND admin --port $MONGO_REPLICA_PORT --eval "$INIT_USER_CMD"; \
# Keep the container running
echo "REPLICA SET ONLINE"; wait $MONGOD_PID;